#!/usr/bin/env python3
"""
Merge freshly fetched holder data with existing zro_data.json labels.
Preserves: labels, types, fresh_wallets metadata, flows, chains config, etc.
Updates: balances, total counts, timestamp.
"""
import json, os, time
from utils import atomic_json_dump

DIR = os.path.dirname(os.path.abspath(__file__))

def load_json(path):
    with open(path) as f:
        return json.load(f)

def save_json(path, data):
    atomic_json_dump(data, path)

def main():
    holders_path = os.path.join(DIR, "holders_multichain.json")
    data_path = os.path.join(DIR, "zro_data.json")

    if not os.path.exists(holders_path):
        print("❌ holders_multichain.json not found — run fetch_holders.py first")
        return

    fresh = load_json(holders_path)
    existing = load_json(data_path)

    # Build label map from existing data
    label_map = {}
    for h in existing.get("top_holders", []):
        addr = h["address"].lower()
        if h.get("label") or h.get("type"):
            label_map[addr] = {
                "label": h.get("label", ""),
                "type": h.get("type", ""),
                "funded_by": h.get("funded_by"),
                "cb_first_funded": h.get("cb_first_funded"),
                "cb_last_funded": h.get("cb_last_funded"),
                "cb_total_received": h.get("cb_total_received"),
            }

    # Build new top_holders from fresh data, preserving labels
    new_holders = []
    for h in fresh.get("holders", []):
        addr = h["address"].lower()
        entry = {
            "address": addr,
            "balances": h["balances"],
            "label": "",
            "type": ""
        }
        # Preserve existing labels and metadata
        if addr in label_map:
            entry["label"] = label_map[addr]["label"]
            entry["type"] = label_map[addr]["type"]
            # Preserve CB Prime metadata, funded_by, wallet_created, and last_flow
            for key in ("funded_by", "wallet_created", "last_flow", "last_flow_amount", "cb_first_funded", "cb_last_funded", "cb_total_received"):
                if label_map[addr].get(key) is not None:
                    entry[key] = label_map[addr][key]

        new_holders.append(entry)

    # Build balance map from existing data (to preserve balances for labeled wallets not in fresh)
    balance_map = {}
    for h in existing.get("top_holders", []):
        addr = h["address"].lower()
        balance_map[addr] = h.get("balances", {})

    # Ensure all labeled addresses are present (even if not in fresh data)
    fresh_addrs = {h["address"].lower() for h in new_holders}
    for addr, lbl in label_map.items():
        if addr not in fresh_addrs:
            # Keep labeled address with ORIGINAL balances (not empty)
            new_holders.append({
                "address": addr,
                "balances": balance_map.get(addr, {}),
                "label": lbl["label"],
                "type": lbl["type"]
            })

    # Apply Whale labels: >5M ZRO, no existing label
    for h in new_holders:
        total = sum(h["balances"].values())
        if total > 5_000_000 and not h["label"]:
            h["label"] = "Whale"
            h["type"] = "WHALE"

    # Sort by total balance descending
    new_holders.sort(key=lambda x: sum(x["balances"].values()), reverse=True)

    # Dedup: keep first entry per address (highest balance since sorted)
    seen_addrs = set()
    deduped = []
    for h in new_holders:
        a = h["address"].lower()
        if a not in seen_addrs:
            seen_addrs.add(a)
            deduped.append(h)
    dup_count = len(new_holders) - len(deduped)
    if dup_count:
        print(f"   🔄 Removed {dup_count} duplicate holders")
    new_holders = deduped

    # Remove zero-balance holders
    before = len(new_holders)
    new_holders = [h for h in new_holders if sum(h.get("balances", {}).values()) > 0]
    zero_rm = before - len(new_holders)
    if zero_rm:
        print(f"   🧹 Removed {zero_rm} zero-balance holders")

    # Flows: preserve existing (generated by generate_flows.py with real on-chain data)
    # Don't overwrite with fake data — generate_flows.py handles this separately
    if "flows" not in existing:
        existing["flows"] = {}

    # Update existing data structure
    existing["top_holders"] = new_holders
    existing["total_supply"] = sum(
        c.get("supply", 0) for c in existing.get("chains", {}).values()
    )
    existing["meta"]["generated"] = time.strftime("%Y-%m-%dT%H:%M:%SZ")

    # Update chain holder counts from fresh data
    chain_stats = fresh.get("chain_stats", {})
    for chain_key, stats in chain_stats.items():
        if chain_key in existing.get("chains", {}):
            existing["chains"][chain_key]["holders"] = stats.get("holders_gt10", 0)

    # ── Data Validation ──
    warnings = []
    errors = []

    # Check: holder count didn't drop more than 50%
    old_count = len(label_map)  # how many labeled we had
    new_count = len(new_holders)
    if old_count > 100 and new_count < old_count * 0.5:
        errors.append(f"Holder count dropped {old_count} → {new_count} (>50% drop!)")

    # Check: top holder balance sanity
    if new_holders:
        top_bal = sum(new_holders[0].get("balances", {}).values())
        if top_bal <= 0:
            errors.append(f"Top holder has 0 balance: {new_holders[0]['address']}")

    # Check: labeled wallets preserved
    new_labeled = sum(1 for h in new_holders if h.get("label"))
    old_labeled = sum(1 for v in label_map.values() if v.get("label"))
    if old_labeled > 10 and new_labeled < old_labeled * 0.8:
        warnings.append(f"Labels dropped: {old_labeled} → {new_labeled}")

    # Check: total supply sanity
    total = existing.get("total_supply", 0)
    if total <= 0:
        warnings.append("Total supply is 0")

    # Print validation results
    if warnings:
        for w in warnings:
            print(f"   ⚠️ WARNING: {w}")
    if errors:
        for e in errors:
            print(f"   ❌ ERROR: {e}")
        print("   🛑 Aborting save due to data validation errors!")
        print("   Fix the issues and re-run, or use FORCE_SAVE=1 to override")
        if not os.environ.get("FORCE_SAVE"):
            return

    save_json(data_path, existing)

    print(f"✅ Updated zro_data.json")
    print(f"   Holders: {len(new_holders)}")
    print(f"   Labeled: {new_labeled}")
    print(f"   Generated: {existing['meta']['generated']}")
    if not warnings and not errors:
        print(f"   ✅ All validation checks passed")

if __name__ == "__main__":
    main()
