#!/usr/bin/env python3
"""
Merge freshly fetched holder data with existing zro_data.json labels.
Preserves: labels, types, fresh_wallets metadata, flows, chains config, etc.
Updates: balances, total counts, timestamp.
"""
import json, os, time, random

random.seed(int(time.time()))

DIR = os.path.dirname(os.path.abspath(__file__))

def load_json(path):
    with open(path) as f:
        return json.load(f)

def save_json(path, data):
    with open(path, 'w') as f:
        json.dump(data, f)

def main():
    holders_path = os.path.join(DIR, "holders_multichain.json")
    data_path = os.path.join(DIR, "zro_data.json")

    if not os.path.exists(holders_path):
        print("❌ holders_multichain.json not found — run fetch_holders.py first")
        return

    fresh = load_json(holders_path)
    existing = load_json(data_path)

    # Build label map from existing data
    label_map = {}
    for h in existing.get("top_holders", []):
        addr = h["address"].lower()
        if h.get("label") or h.get("type"):
            label_map[addr] = {
                "label": h.get("label", ""),
                "type": h.get("type", "")
            }

    # Build new top_holders from fresh data, preserving labels
    new_holders = []
    for h in fresh.get("holders", []):
        addr = h["address"].lower()
        entry = {
            "address": addr,
            "balances": h["balances"],
            "label": "",
            "type": ""
        }
        # Preserve existing labels
        if addr in label_map:
            entry["label"] = label_map[addr]["label"]
            entry["type"] = label_map[addr]["type"]

        new_holders.append(entry)

    # Build balance map from existing data (to preserve balances for labeled wallets not in fresh)
    balance_map = {}
    for h in existing.get("top_holders", []):
        addr = h["address"].lower()
        balance_map[addr] = h.get("balances", {})

    # Ensure all labeled addresses are present (even if not in fresh data)
    fresh_addrs = {h["address"].lower() for h in new_holders}
    for addr, lbl in label_map.items():
        if addr not in fresh_addrs:
            # Keep labeled address with ORIGINAL balances (not empty)
            new_holders.append({
                "address": addr,
                "balances": balance_map.get(addr, {}),
                "label": lbl["label"],
                "type": lbl["type"]
            })

    # Apply Whale labels: >5M ZRO, no existing label
    for h in new_holders:
        total = sum(h["balances"].values())
        if total > 5_000_000 and not h["label"]:
            h["label"] = "Whale"
            h["type"] = "WHALE"

    # Sort by total balance descending
    new_holders.sort(key=lambda x: sum(x["balances"].values()), reverse=True)

    # Flows: preserve existing (generated by generate_flows.py with real on-chain data)
    # Don't overwrite with fake data — generate_flows.py handles this separately
    if "flows" not in existing:
        existing["flows"] = {}

    # Update existing data structure
    existing["top_holders"] = new_holders
    existing["total_supply"] = sum(
        c.get("supply", 0) for c in existing.get("chains", {}).values()
    )
    existing["meta"]["generated"] = time.strftime("%Y-%m-%dT%H:%M:%SZ")

    # Update chain holder counts from fresh data
    chain_stats = fresh.get("chain_stats", {})
    for chain_key, stats in chain_stats.items():
        if chain_key in existing.get("chains", {}):
            existing["chains"][chain_key]["holders"] = stats.get("holders_gt10", 0)

    save_json(data_path, existing)

    print(f"✅ Updated zro_data.json")
    print(f"   Holders: {len(new_holders)}")
    print(f"   Labeled: {sum(1 for h in new_holders if h['label'])}")
    print(f"   Generated: {existing['meta']['generated']}")

if __name__ == "__main__":
    main()
